### ISSUE TITLE
Version identifier in TOML before releasing v1.0?

### ISSUE THREAD

**Issue by rwitzel** [toml-lang/toml#661] opened 2019-08-27 16:32 UTC
Many specifications for document allow a version identifier at the beginning of the document ( in YAML, XML and JSON documents - think of AWS JSONs).

Such an identifier might prevent conflicts and compatibility issues in the feature.

Does it make sense to have such a version identifier for TOML as well?

**Comment by pradyunsg** [comment] 2019-08-27 17:46
Thanks for filing this issue!

This was discussed in #522. Closing as a duplicate of the same.

**Closed by pradyunsg** 2019-08-27 17:46 UTC
