### ISSUE TITLE
What about allowing special characters in bare-keys?

### ISSUE THREAD

**Issue by TheElectronWill** [toml-lang/toml#401] opened 2016-03-21 15:05 UTC
Allowing special characters, and in particular those with an accent (like é, è, à, ï) would be very practical for many languages. It would save us from quoting half of the keys, like this:
```toml
"météo" = "weather"
"été" = "summer"
hiver = "winter"
```
I don't really see any drawback of allowing accents, but please tell me if I'm wrong.

**Comment by BurntSushi** [comment] 2016-03-21 15:50
dupe of #337

**Comment by TheElectronWill** [comment] 2016-03-21 16:30
My mistake, I should have searched more ^^
I've read most of the explainations about the choice of restricting bare-keys, but that doesn't completely satisfy me. Maybe I'll add an option in my lib to allow any character but `.[] =` in bare-keys.

**Closed** 2016-03-21 16:32 UTC
