### ISSUE TITLE
Assigning values via an array-of-tables like syntax

### ISSUE THREAD

**Issue by lizelive** [toml-lang/toml#896] opened 2022-05-04 01:45 UTC
[^gap]:  `# long gap` contains relevant configuration for each preceding

if i have 3 objects i can define them like this

```toml
[[long.path.to.array]]
value = 1
# long space defining stuff for preceding
[[long.path.to.array]]
value = 2
# long space defining stuff for preceding
[[long.path.to.array]]
value = 3
# long space defining stuff for preceding
```
which is good

also works well if the short thing works if `long.path.to.array` is a table

```toml
long.path.to.table.1 = 1
# long space defining stuff for preceding
long.path.to.table.2 = 2
# long space defining stuff for preceding
[long.path.to.table.3]
sometimes = 1
config = 2
is = 3
big = 4
# long space defining stuff for preceding
```

but if the thing i want to store is
```toml
long.path.to.array = [1, 2, { sometimes = 1, config = 2, is = 3, big = 4}]
```

their is no equivalent.

proposal is to support

```toml
[long.path.to.array]=1
# long gap
[long.path.to.array]=2
# long gap
[[long.path.to.array]]
sometimes = 1
config = 2
is = 3
big = 4
# long gap
```

this make mixed arrays a huge pain in 
for a lot of the configs I write at work, spacing out the assignment is important for readability's sake and just for symetry
and alt would be support assigning to empty

```toml
[[long.path.to.array]]
=1
# long space defining stuff for preceding
[[long.path.to.array]]
=2
# long space defining stuff for preceding
[[long.path.to.array]]
sometimes = 1
config = 2
is = 3
big = 4
# long space defining stuff for preceding
```

allowing assigment to empty is good becuse it means i can translate more json to toml
right now no way to support the json document
```json
"hello world"
```

**Comment by pradyunsg** [comment] 2022-05-04 07:36
I don't think this will be particularly valuable, once inline tables are allowed to span multiple lines and have trailing commas (see #516).

At that point, you can "just" have such values declared inline and things will... for the most part... "just work".

**Comment by eksortso** [comment] 2022-05-04 13:04
I floated a similar idea some time ago. It didn't go down well.

By design, a TOML document always maps to a table. So some JSON documents, like the `"hello world"` example, have no equivalents in TOML.

**Closed** 2022-10-03 23:02 UTC
