### ISSUE TITLE
Nested arrays of tables

### ISSUE THREAD

**Issue by yasammez** [toml-lang/toml#353] opened 2015-09-19 16:35 UTC
Hi everyone!

TOML has arrays:

``` toml
array = [ [1, 0], [0, 1] ]
```

``` json
"array":[ [ 1, 0], [0, 1] ]
```

TOML has tables:

``` toml
[table]
value = 1
```

``` json
"table":{ "value":1 }
```

TOML even has arraytables:

``` toml
[[arraytable]]
value = 1
[[arraytable]]
value = 2
```

``` json
"arraytable":[ { "value":1 }, { "value":2} ]
```

But is there any way to do something like

``` json
"nested_array_table":[ 
  [ { "value":1 }, {"value":0} ], 
  [ {"value":0}, {"value":1, "comment":"bottom right diagonal element"} ] ]
```

in TOML? If so, how can I do this? If not, why can't I do this?

I understand that there is always a way around this, by for instance flattening arrays

``` toml
[[matrix]]
value = 1
[[matrix]]
value = 0
[[matrix]]
value = 1
[[matrix]]
value = 0
comment = "bottom right diagonal element"
```

or introducing _filler_ structs:

``` toml
[[matrix.row]]
  [[matrix.row.column]]
  value = 1
  [[matrix.row.column]]
  value = 0
[[matrix.row]]
  [[matrix.row.column]]
  value = 1
  [[matrix.row.column]]
  value = 0
  comment = "bottom right diagonal element"
```

However, none of these seems really appropriate. Also, in that case, TOML would be strict less expressive than JSON, which is kind of a pitty, since JSON is so darn unreadable.

**Comment by fischmax** [comment] 2015-09-23 15:24
One possible idea for an extension, which, I admit, scales not very well, would be to add additional layers of brackets around the table names: one for each level of array depth:

```toml
[[[matrix]]]
value = 1
[[matrix]]
value = 0
[[[matrix]]]
value = 0
[[matrix]]
value = 1
comment = "bottom right diagonal element"
```
This would be equivalent to the following JSON:

```json
"matrix":[ [ { "value":1 }, { "value":0 } ], [ { "value":0 }, { "value":1, "comment":"bottom right diagonal element" } ] ]
```

**Comment by sanmai-NL** [comment] 2016-05-18 07:15
Why does the lack of a matrix notation make TOML strictly less expressive than JSON? I'm interested to know, since I'm not aware of any such notation in JSON.

**Comment by ChristianSi** [comment] 2016-05-19 09:07
@fischmax: TOML has inline tables, so you should be able to write your example as follows (I think):

    nested_array_table = [ 
        [ {value = 1}, {value  = 0} ], 
        [ {value = 0}, {value = 1, comment = bottom right diagonal element} ] ]

**Comment by franklinyu** [comment] 2016-06-14 18:01
In #309 @jodastephen suggested an alternative grammar for array table:

```toml
[analyzers.filter]
  [#]
  type = "icu-tokenizer"

  [#]
  type = "lowercase"

  [#]
  type = "length"
  min = 2
  max = 35
```

If this is accepted, it can be easily extended to allow n-dimension matrix:

```toml
[nested_array_table]
  [#]
    [##]
    value = 1
    [##]
    value = 0

  [#]
    [##]
    value = 0
    [##]
    value = 1
    comment = "bottom right diagonal element"
```

**Comment by nikitindiz** [comment] 2017-06-07 13:19
Any workaround?

**Comment by pradyunsg** [comment] 2017-11-17 13:39
IMO, this issue is a duplicate of #309. It can be closed in favour of that.

**Comment by pradyunsg** [comment] 2018-05-23 18:13
Closing as a duplicate of #309.

**Closed by pradyunsg** 2018-05-23 18:13 UTC

**Comment by tmccombs** [comment] 2021-08-15 03:26
I disagree that this is a duplicate of #309. Related, certainly, but not a duplicate. Different syntax for arrays of tables, including several that were proposed on that thread, won't necessarily allow arrays of arrays of tables, and likewise support for arrays of arrays of tables could potentially be added without changing the existing syntax for arrays of tables.
