### ISSUE TITLE
How should parser deal with float out of range 64-bit?

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#618] opened 2019-05-06 19:20 UTC
`1e1000` should be parsed as `inf`, or throw an error (like dealing with `10000000000000000000000000000000000` integer, which is out of range signed long)?

If it's an error, maybe the official test example should be changed (or [delete](https://github.com/toml-lang/toml/issues/377)):

https://github.com/toml-lang/toml/blob/e741e487ea8c7e22e6fcd778ae3d89cfff8a95dd/examples/example-v0.4.0.toml#L152

**Comment by pradyunsg** [comment] 2019-05-07 04:18
Duplicate of #538

**Closed by pradyunsg** 2019-05-07 04:18 UTC
